version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
      - /src/node_modules
    # command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development


  mongodb:
    image: mongo:4.4-focal
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db

volumes:
  db-data:      